[build]
  base = "client"
  publish = "dist"
  # explicitly install devDependencies even if NODE_ENV=production
  command = "npm ci --include=dev && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# remove or avoid setting NODE_ENV here; Netlify sets it automatically for production
# If you previously set it below, remove that block or comment it out.
# [context.production.environment]
#   NODE_ENV = "production"
#
# [context.deploy-preview.environment]
#   NODE_ENV = "development"
#
# [context.branch-deploy.environment]
#   NODE_ENV = "development"
