version: '3.9'
services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: liveboard
      POSTGRES_PASSWORD: liveboard
      POSTGRES_DB: liveboard
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build:
      context: ..
      dockerfile: server/Dockerfile
    depends_on:
      - db
    environment:
      NODE_ENV: production
      PORT: 4000
      CLIENT_ORIGIN: http://localhost:8080
      DATABASE_URL: postgresql://liveboard:liveboard@db:5432/liveboard?schema=public
      JWT_SECRET: change_me
      JWT_REFRESH_SECRET: change_me_refresh
    ports:
      - "4000:4000"

  client:
    build:
      context: ..
      dockerfile: client/Dockerfile
    environment:
      VITE_API_URL: http://localhost:4000
      VITE_WEBSOCKET_URL: http://localhost:4000
    ports:
      - "5173:80"

  nginx:
    image: nginx:1.25-alpine
    depends_on:
      - client
      - server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"

volumes:
  db_data:


